[programs.localnet]
solana_escrow_anchor = "3aaLZLTyVHEJDqnySpxJjAffUsJuDm95U2BHiRPYoVTc"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/dayofthetech/Alberto-Q1-Solana-2023/Cluster 2/solana-escrow-anchor/tests/keys/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-setup = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g 'Setup'"
test-alice = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g 'Alice'"
test-bob = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts -g 'Bob'"
