[features]
seeds = false
skip-lint = false
[programs.localnet]
deposit = "2c5b6vwytgEr3nR7spg1kLtU6CicK5Aepa2SwKV7g52T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/dayofthetech/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
